plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android
    id 'kotlin-parcelize'
    alias libs.plugins.google.gms.google.services
    alias libs.plugins.google.firebase.crashlytics
    alias libs.plugins.google.firebase.firebase.perf
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    compileSdk 37

    defaultConfig {
        applicationId "com.example.myapp"
        minSdk 23
        targetSdk 37
        versionCode 1

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled true // Enabled for production
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
        viewBinding true
    }
    namespace 'com.example.myapp'
}

dependencies {
    // Core AndroidX & UI
    implementation libs.androidx.appcompat
    implementation libs.androidx.annotation
    implementation libs.androidx.constraintlayout
    implementation libs.material
    implementation libs.androidx.cardview
    implementation libs.androidx.activity
    
    // Lifecycle & Navigation
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.viewmodel
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
    implementation libs.androidx.preference
    
    // Firebase
    implementation libs.firebase.database
    implementation libs.firebase.crashlytics
    implementation libs.firebase.analytics
    implementation libs.firebase.perf
    implementation libs.firebase.storage
    implementation libs.firebase.ui.storage
    implementation(platform(libs.firebase.bom))

    // Add the dependency for the Firebase Authentication library
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation(libs.google.firebase.auth)

    // Compose (Note: Requires Kotlin files to function)
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.material3.windowSizeClass
    implementation libs.androidx.compose.uiToolingPreview
    implementation libs.androidx.compose.runtimeLivedata
    implementation libs.androidx.compose.runtimeRxjava2
    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.compose.materialIconsCore
    debugImplementation libs.androidx.compose.uiTooling
    debugImplementation libs.androidx.compose.uiTestManifest
    androidTestImplementation libs.androidx.compose.uiTestJunit4

    // Other Libraries
    implementation libs.android.gif.drawable
    implementation libs.androidx.paging.compose
    implementation libs.androidx.core
    implementation libs.play.services.cronet
    implementation libs.volley
    implementation libs.glide
    annotationProcessor libs.compiler
    
    // Testing
    testImplementation libs.junit
}

configurations.implementation {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}
